changelog:
  categories:
    - title: Dependencies 🔗
      labels:
        - dependency
    - title: New Features 🎉
      labels:
        - new feature
    - title: Improvements 💪🏼
      labels:
        - enhancement
    - title: Fixes 🛠
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
