changelog:
  categories:
    - title: Dependencies 🛠
      labels:
        - dependencies
    - title: New Features 🎉
      labels:
        - new-feature
    - title: Improvements 💪🏼
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
