name: Lint

on:
  push:
    branches: [main]

jobs:
  lint:
    name: 'Lint ✅'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - uses: actions/cache@v4
      with:
        key: bun-cache
        path: ~/.bun/install/cache
    - run: bun install
    - run: bun run lint
