name: Staging

on:
  push:
    branches:
        - main

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-web
      cancel-in-progress: true
    permissions:
      pages: write
      id-token: write
      contents: write
      discussions: write
    environment:
      name: staging
      url: https://dev.ppocgen.com
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name GitHub_Runner
          echo 'dev.ppocgen.com' > ./static/CNAME
      - run: bun install
      - run: bun run build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          NODE_ENV: 'production'
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'
      - uses: actions/deploy-pages@v4
        id: deployment