name: Staging

on:
  push:
    branches:
        - main

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-web-staging
      cancel-in-progress: true
    permissions:
      contents: write
    environment:
      name: staging
      url: https://dev.ppocgen.com
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
        env:
          NODE_ENV: 'production'
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dev-ppoc-gen
          directory: build
